FROM lxh01/wine-vnc:msyh

# 清理环境
RUN sudo rm -rf /tmp/.X0-lock

ENV WINEDEBUG=fixme-all

# 根据传入参数安装微信和wxhelper.dll
ARG WECHAT_URL=https://github.com/tom-snow/wechat-windows-versions/releases/download/v3.9.5.81/WeChatSetup-3.9.5.81.exe
ARG WXHELPER_URL=https://github.com/ttttupup/wxhelper/releases/download/3.9.5.81-v11/wxhelper.dll

WORKDIR /home/app/.wine/drive_c

# 加载注入器
COPY DllInjector.exe DllInjector.exe
RUN sudo chown app:app DllInjector.exe && sudo chmod a+x DllInjector.exe

# 下载微信
ADD ${WECHAT_URL} WeChatSetup.exe
RUN sudo chown app:app WeChatSetup.exe  && sudo chmod a+x WeChatSetup.exe

# 下载wxhelper.dll
ADD ${WXHELPER_URL} wxhelper.dll
RUN sudo chown app:app wxhelper.dll

# 安装微信
COPY install-wechat.sh install-wechat.sh
RUN sudo chmod a+x install-wechat.sh && ./install-wechat.sh
RUN rm -rf WeChatSetup.exe && rm -rf install-wechat.sh

# 安装改版本依赖
ADD https://www.python.org/ftp/python/3.9.10/python-3.9.10-amd64.exe python-3.9.10-amd64.exe
RUN bash -c 'nohup /entrypoint.sh 2>&1 &' && \
  sleep 10 && \
  sudo chown app:app python-3.9.10-amd64.exe && \
  wine "c:\python-3.9.10-amd64.exe" /quite /passive TargetDir=C:\PYTHON InstallAllUsers=1 PrependPath=1 && \
  rm -rf python-3.9.10-amd64.exe && \
  wine pip install pymem
COPY version.py version.py
RUN sudo chmod +x version.py

EXPOSE 5900 19088

COPY cmd.sh /cmd.sh
RUN sudo chmod +x /cmd.sh
CMD ["/cmd.sh"]